let DATA,breakKey='office',charts=new Map();const $=s=>document.querySelector(s),fmt=n=>n.toLocaleString(),pct=(a,b)=>b?100*a/b:0,month=d=>d.slice(0,7),monthLabel=m=>new Date(m+'-02T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'});
fetch('data.json').then(r=>r.json()).then(d=>{d.records=d.records.map(r=>({firstServiceDate:r[0],office:d.offices[r[1]],active:r[2],cancellationMonth:r[3],source:d.sources[r[4]],customerType:r[5]?'Commercial':'Residential',count:r[6]}));DATA=d;$('#asof').textContent='Data through '+new Date(d.generatedAt).toLocaleString();$('#allactive').textContent=fmt(d.validation.allActiveCustomersExcludingNashville);const max=d.records.reduce((m,r)=>r.firstServiceDate>m?r.firstServiceDate:m,'');$('#cutoff').max=max;$('#cutoff').value=max;fill('#office',[...new Set(d.records.map(r=>r.office))]);fill('#type',[...new Set(d.records.map(r=>r.customerType))]);fill('#source',[...new Set(d.records.map(r=>r.source))].sort());render()});
function fill(sel,a){for(const x of a.sort()){let o=document.createElement('option');o.value=o.textContent=x;$(sel).append(o)}}
for(const s of ['#cutoff','#office','#type','#source'])$(s).addEventListener('change',render);$('#reset').onclick=()=>{for(const s of ['#office','#type','#source'])$(s).value='';$('#cutoff').value=$('#cutoff').max;render()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');breakKey=b.dataset.break;render()});
function selected(ignoreCutoff=false){if(!DATA)return[];let c=$('#cutoff').value,o=$('#office').value,t=$('#type').value,s=$('#source').value;return DATA.records.filter(r=>(ignoreCutoff||r.firstServiceDate<=c)&&(!o||r.office===o)&&(!t||r.customerType===t)&&(!s||r.source===s))}
function render(){if(!DATA)return;let rs=selected(),base=rs.reduce((a,r)=>a+r.count,0),active=rs.reduce((a,r)=>a+r.active*r.count,0),rate=pct(active,base);$('#rate').textContent=rate.toFixed(1)+'%';$('#attr').textContent=(100-rate).toFixed(1)+'% attrition';$('#base').textContent=fmt(base);$('#active').textContent=fmt(active);$('#churn').textContent=fmt(base-active);breakdown(rs);detail(rs);trend();monthly(rs)}
function breakdown(rs){let m={};for(const r of rs){let k=r[breakKey]||'Unknown',x=m[k]||(m[k]=[0,0]);x[0]+=r.count;x[1]+=r.active*r.count}$('#breaklabel').textContent={office:'Office',source:'Sale source',customerType:'Type'}[breakKey];let a=Object.entries(m).sort((x,y)=>y[1][0]-x[1][0]);$('#breakdown').innerHTML=a.length?a.slice(0,18).map(([k,[b,ac]])=>`<tr><td>${esc(k)}</td><td>${fmt(b)}</td><td>${pct(ac,b).toFixed(1)}%</td><td>${(100-pct(ac,b)).toFixed(1)}%</td></tr>`).join(''):'<tr><td colspan="4" class="empty">No customers match</td></tr>'}
function detail(rs){let m={};for(const r of rs){let k=month(r.firstServiceDate),x=m[k]||(m[k]=[0,0]);x[0]+=r.count;x[1]+=r.active*r.count}let a=Object.entries(m).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,24);$('#detail').innerHTML=a.length?a.map(([k,[b,ac]])=>`<tr><td>${monthLabel(k)}</td><td>${fmt(b)}</td><td>${fmt(ac)}</td><td>${pct(ac,b).toFixed(1)}%</td><td>${(100-pct(ac,b)).toFixed(1)}%</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No customers match</td></tr>'}
function trend(){let all=selected(true),end=$('#cutoff').value.slice(0,7),months=[],d=new Date(end+'-01T12:00:00');for(let i=23;i>=0;i--){let x=new Date(d);x.setMonth(x.getMonth()-i);months.push(x.toISOString().slice(0,7))}let vals=months.map(m=>{let rs=all.filter(r=>r.firstServiceDate<=m+'-31'),b=rs.reduce((a,r)=>a+r.count,0),ac=rs.reduce((a,r)=>a+r.active*r.count,0);return pct(ac,b)});line($('#trend'),months,vals)}
function monthly(rs){let end=$('#cutoff').value.slice(0,7),months=[],d=new Date(end+'-01T12:00:00');for(let i=17;i>=0;i--){let x=new Date(d);x.setMonth(x.getMonth()-i);months.push(x.toISOString().slice(0,7))}let vals=months.map(m=>rs.filter(r=>r.cancellationMonth===m).reduce((a,r)=>a+r.count,0));bars($('#monthly'),months,vals)}
function setup(c){let w=c.clientWidth||800,h=Math.max(230,Math.min(320,w*.34)),dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;c.style.height=h+'px';let x=c.getContext('2d');x.scale(dpr,dpr);return[x,w,h]}
function axes(x,w,h,max,percent=false){x.strokeStyle='#dfe7f0';x.fillStyle='#6b7a90';x.font='11px system-ui';for(let i=0;i<=4;i++){let y=15+(h-50)*i/4;x.beginPath();x.moveTo(45,y);x.lineTo(w-10,y);x.stroke();let v=max*(1-i/4);x.fillText(percent?v.toFixed(0)+'%':Math.round(v).toLocaleString(),2,y+4)}}
function bind(c,points,kind){charts.set(c,{points,kind});if(c.dataset.tip)return;c.dataset.tip=1;for(const ev of ['mousemove','click','touchstart'])c.addEventListener(ev,e=>{let r=c.getBoundingClientRect(),client=e.touches?e.touches[0]:e,x=client.clientX-r.left,y=client.clientY-r.top,ch=charts.get(c),p=ch.points.reduce((a,b)=>Math.hypot(b.x-x,b.y-y)<Math.hypot(a.x-x,a.y-y)?b:a,ch.points[0]);if(!p||Math.abs(p.x-x)>30){hideTip();return}showTip(c,p.x,p.y,`${monthLabel(p.label)}<b>${ch.kind==='percent'?p.value.toFixed(1)+'%':fmt(p.value)}</b>`)}) ;c.addEventListener('mouseleave',hideTip)}
function showTip(c,x,y,html){let t=$('#tooltip'),r=c.getBoundingClientRect();t.innerHTML=html;t.style.display='block';t.style.left=Math.min(innerWidth-t.offsetWidth-8,r.left+x+12)+'px';t.style.top=Math.max(8,r.top+y-t.offsetHeight-10)+'px'}function hideTip(){$('#tooltip').style.display='none'}
function line(c,labels,vals){let[x,w,h]=setup(c);axes(x,w,h,100,true);if(!vals.length)return;let points=vals.map((v,i)=>({x:45+(w-65)*i/(vals.length-1||1),y:15+(h-50)*(1-v/100),value:v,label:labels[i]}));x.strokeStyle='#1478f2';x.lineWidth=2;x.beginPath();points.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.stroke();x.fillStyle='#1478f2';points.forEach((p,i)=>{x.beginPath();x.arc(p.x,p.y,3,0,7);x.fill();if(i%3===0||i===points.length-1){x.fillStyle='#506078';x.fillText(monthLabel(p.label),Math.max(45,p.x-15),h-10);x.fillStyle='#1478f2'}});bind(c,points,'percent')}
function bars(c,labels,vals){let[x,w,h]=setup(c),max=Math.max(4,...vals)*1.15;axes(x,w,h,max,false);let bw=(w-65)/vals.length*.62,points=[];vals.forEach((v,i)=>{let px=45+(w-65)*i/vals.length+(w-65)/vals.length*.19,py=15+(h-50)*(1-v/max);x.fillStyle='#df4c57';x.fillRect(px,py,bw,h-35-py);points.push({x:px+bw/2,y:py,value:v,label:labels[i]});if(i%3===0||i===vals.length-1){x.fillStyle='#506078';x.fillText(monthLabel(labels[i]),px,h-10)}});bind(c,points,'count')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}window.addEventListener('resize',()=>DATA&&render());
