let DATA,breakKey='office',charts=new Map();const $=s=>document.querySelector(s),fmt=n=>n.toLocaleString(),pct=(a,b)=>b?100*a/b:0,month=d=>d.slice(0,7),dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}),monthLabel=m=>new Date(m+'-02T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'});
fetch('data.json').then(r=>r.json()).then(d=>{d.records=d.records.map(r=>({firstServiceDate:r[0],office:d.offices[r[1]],active:r[2],cancellationMonth:r[3],source:d.sources[r[4]],customerType:r[5]?'Commercial':'Residential',count:r[6]}));DATA=d;$('#asof').textContent='Data through '+new Date(d.generatedAt).toLocaleString();$('#allactive').textContent=fmt(d.validation.allActiveCustomerRecords);const asOfLabel=new Date(d.generatedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});d.asOfLabel=asOfLabel;$('#trend-title').textContent='Current active rate by first-service month (cohorts 12+ months old)';$('#trend-subtitle').textContent='Each point is one monthly first-service cohort, all 11 offices. Every customer shown has been a customer for at least a year as of '+asOfLabel+', the data timestamp. The filters above do not change this line.';const min=d.records.reduce((m,r)=>r.firstServiceDate<m?r.firstServiceDate:m,'9999'),max=d.records.reduce((m,r)=>r.firstServiceDate>m?r.firstServiceDate:m,'');for(const s of ['#start','#end','#cutoff']){$(s).min=min;$(s).max=max}$('#start').value=max.slice(0,8)+'01';$('#end').value=max;$('#cutoff').value=max;fill('#office',[...new Set(d.records.map(r=>r.office))]);fill('#type',[...new Set(d.records.map(r=>r.customerType))]);fill('#source',[...new Set(d.records.map(r=>r.source))].sort());render()});
function fill(sel,a){for(const x of a.sort()){let o=document.createElement('option');o.value=o.textContent=x;$(sel).append(o)}}
const mode=()=>document.querySelector('input[name="mode"]:checked').value;
for(const s of ['#start','#end','#cutoff','#office','#type','#source'])$(s).addEventListener('change',render);document.querySelectorAll('input[name="mode"]').forEach(x=>x.addEventListener('change',()=>{syncMode();render()}));
$('#reset').onclick=()=>{for(const s of ['#office','#type','#source'])$(s).value='';document.querySelector('input[name="mode"][value="range"]').checked=true;$('#start').value=$('#end').max.slice(0,8)+'01';$('#end').value=$('#end').max;$('#cutoff').value=$('#cutoff').max;syncMode();render()};
function syncMode(){let range=mode()==='range';document.querySelectorAll('.range-control').forEach(x=>x.hidden=!range);document.querySelector('.cutoff-control').hidden=range}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');breakKey=b.dataset.break;render()});
function baseFiltered(){if(!DATA)return[];let o=$('#office').value,t=$('#type').value,s=$('#source').value;return DATA.records.filter(r=>(!o||r.office===o)&&(!t||r.customerType===t)&&(!s||r.source===s))}
function selected(){let rs=baseFiltered();if(mode()==='cumulative'){let c=$('#cutoff').value;return rs.filter(r=>r.firstServiceDate<=c)}let a=$('#start').value,b=$('#end').value;if(a>b)return[];return rs.filter(r=>r.firstServiceDate>=a&&r.firstServiceDate<=b)}
function render(){if(!DATA)return;let isRange=mode()==='range',invalid=isRange&&$('#start').value>$('#end').value,rs=selected(),base=rs.reduce((a,r)=>a+r.count,0),active=rs.reduce((a,r)=>a+r.active*r.count,0),rate=pct(active,base),label=isRange?`${dateLabel($('#start').value)} - ${dateLabel($('#end').value)}`:`On or before ${dateLabel($('#cutoff').value)}`;$('#selection').classList.toggle('error',invalid);$('#selection').textContent=invalid?'Start date must be on or before end date.':`${isRange?'DATE RANGE':'CUMULATIVE'} · True first completed service ${isRange?'from ':'on or before '}${isRange?label.toLowerCase():dateLabel($('#cutoff').value)}`;$('#metric-title').textContent=isRange?'Selected first-service date range':'Cumulative through selected cutoff';$('#metric-subtitle').textContent=invalid?'Invalid date range':label;for(const id of ['rate','base','active','inactive'])$('#'+id+'-label').textContent=(isRange?'Range cohort ':'Cumulative ')+({rate:'active rate',base:'customers',active:'still active',inactive:'inactive'}[id]);$('#rate').textContent=base?rate.toFixed(1)+'%':'-';$('#attr').textContent=base?(100-rate).toFixed(1)+'% inactive':'No customers match';$('#base').textContent=fmt(base);$('#active').textContent=fmt(active);$('#churn').textContent=fmt(base-active);breakdown(rs);detail(rs);trend();monthly(rs)}
function breakdown(rs){let m={};for(const r of rs){let k=r[breakKey]||'Unknown',x=m[k]||(m[k]=[0,0]);x[0]+=r.count;x[1]+=r.active*r.count}$('#breaklabel').textContent={office:'Office',source:'Sale source',customerType:'Type'}[breakKey];let a=Object.entries(m).sort((x,y)=>y[1][0]-x[1][0]);$('#breakdown').innerHTML=a.length?a.slice(0,18).map(([k,[b,ac]])=>`<tr><td>${esc(k)}</td><td>${fmt(b)}</td><td>${pct(ac,b).toFixed(1)}%</td><td>${(100-pct(ac,b)).toFixed(1)}%</td></tr>`).join(''):'<tr><td colspan="4" class="empty">No customers match</td></tr>'}
function detail(rs){let m={};for(const r of rs){let k=month(r.firstServiceDate),x=m[k]||(m[k]=[0,0]);x[0]+=r.count;x[1]+=r.active*r.count}let a=Object.entries(m).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,36);$('#detail').innerHTML=a.length?a.map(([k,[b,ac]])=>`<tr><td>${monthLabel(k)}</td><td>${fmt(b)}</td><td>${fmt(ac)}</td><td>${fmt(b-ac)}</td><td>${pct(ac,b).toFixed(1)}%</td><td>${(100-pct(ac,b)).toFixed(1)}%</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No customers match</td></tr>'}
function trend(){if(!DATA)return;let cutoff=new Date(DATA.generatedAt);cutoff.setFullYear(cutoff.getFullYear()-1);let m={};for(const r of DATA.records){let k=month(r.firstServiceDate),x=m[k]||(m[k]=[0,0]);x[0]+=r.count;x[1]+=r.active*r.count}let keys=Object.keys(m).sort().filter(k=>{let e=new Date(k+'-01T12:00:00');e.setMonth(e.getMonth()+1);e.setDate(0);return e<=cutoff});let vals=keys.map(k=>{let[b,a]=m[k];return{value:pct(a,b),base:b,active:a}});line($('#trend'),keys,vals,'mature-percent')}
function monthly(rs){let months=[],end=mode()==='range'?$('#end').value.slice(0,7):$('#cutoff').value.slice(0,7),d=new Date(end+'-01T12:00:00');for(let i=17;i>=0;i--){let x=new Date(d);x.setMonth(x.getMonth()-i);months.push(x.toISOString().slice(0,7))}let vals=months.map(m=>rs.filter(r=>r.cancellationMonth===m).reduce((a,r)=>a+r.count,0));bars($('#monthly'),months,vals)}
function setup(c){let w=c.clientWidth||800,h=Math.max(230,Math.min(320,w*.34)),dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;c.style.height=h+'px';let x=c.getContext('2d');x.scale(dpr,dpr);return[x,w,h]}
function axes(x,w,h,max,percent=false){x.strokeStyle='#dfe7f0';x.fillStyle='#6b7a90';x.font='11px system-ui';for(let i=0;i<=4;i++){let y=15+(h-50)*i/4;x.beginPath();x.moveTo(45,y);x.lineTo(w-10,y);x.stroke();let v=max*(1-i/4);x.fillText(percent?v.toFixed(0)+'%':Math.round(v).toLocaleString(),2,y+4)}}
function bind(c,points,kind){charts.set(c,{points,kind});if(c.dataset.tip)return;c.dataset.tip=1;for(const ev of ['mousemove','click','touchstart'])c.addEventListener(ev,e=>{let r=c.getBoundingClientRect(),client=e.touches?e.touches[0]:e,x=client.clientX-r.left,y=client.clientY-r.top,ch=charts.get(c);if(!ch.points.length){hideTip();return}let p=ch.points.reduce((a,b)=>Math.hypot(b.x-x,b.y-y)<Math.hypot(a.x-x,a.y-y)?b:a,ch.points[0]);if(!p||Math.abs(p.x-x)>35){hideTip();return}let prefix=ch.kind==='mature-percent'?'First-service cohort: ':'Cancelled in ';let detail=ch.kind==='mature-percent'?`<b>${p.value.toFixed(1)}% active</b>${fmt(p.active)} of ${fmt(p.base)} customers still active, status as of ${DATA.asOfLabel}`:`<b>${fmt(p.value)} customers</b>`;showTip(c,p.x,p.y,`${prefix}${monthLabel(p.label)}${detail}`)}) ;c.addEventListener('mouseleave',hideTip)}
function showTip(c,x,y,html){let t=$('#tooltip'),r=c.getBoundingClientRect();t.innerHTML=html;t.style.display='block';t.style.left=Math.min(innerWidth-t.offsetWidth-8,r.left+x+12)+'px';t.style.top=Math.max(8,r.top+y-t.offsetHeight-10)+'px'}function hideTip(){$('#tooltip').style.display='none'}
function line(c,labels,vals,kind){let[x,w,h]=setup(c);axes(x,w,h,100,true);let valid=vals.map((v,i)=>v==null?null:{x:45+(w-65)*i/(vals.length-1||1),y:15+(h-50)*(1-(typeof v==='object'?v.value:v)/100),value:typeof v==='object'?v.value:v,base:v&&typeof v==='object'?v.base:undefined,active:v&&typeof v==='object'?v.active:undefined,label:labels[i]}).filter(Boolean);if(!valid.length){x.fillStyle='#6b7a90';x.fillText('No customers match this date selection',55,h/2);bind(c,[],kind);return}x.strokeStyle='#1478f2';x.lineWidth=2;x.beginPath();valid.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.stroke();x.fillStyle='#1478f2';let stride=w<500?6:3;valid.forEach((p,i)=>{x.beginPath();x.arc(p.x,p.y,3,0,7);x.fill();let last=i===valid.length-1;if((i%stride===0&&i<valid.length-2)||last){x.fillStyle='#506078';x.fillText(monthLabel(p.label),last?Math.min(p.x-15,w-58):Math.max(45,p.x-15),h-10);x.fillStyle='#1478f2'}});bind(c,valid,kind)}
function bars(c,labels,vals){let[x,w,h]=setup(c),max=Math.max(4,...vals)*1.15;axes(x,w,h,max,false);let bw=(w-65)/vals.length*.62,points=[];vals.forEach((v,i)=>{let px=45+(w-65)*i/vals.length+(w-65)/vals.length*.19,py=15+(h-50)*(1-v/max);x.fillStyle='#df4c57';x.fillRect(px,py,bw,h-35-py);points.push({x:px+bw/2,y:py,value:v,label:labels[i]});if(i%3===0||i===vals.length-1){x.fillStyle='#506078';x.fillText(monthLabel(labels[i]),px,h-10)}});bind(c,points,'count')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}window.addEventListener('resize',()=>DATA&&render());
